(define (problem delivery-problem)
    (:domain delivery-domain)
    (:objects G1 G2 G3 G4 G5 G6 G7 G8 G9 G10 package1 gripper1 car1 key1 robot1)
    (:init 
        (state G1)
        (state G2)
        (state G3)
        (state G4)
        (state G5)
        (state G6)
        (state G7)
        (state G8)
        (state G9)
        (state G10)
        
        (package package1)
        (robot robot1)
        (gripper gripper1)
        (car car1)
        (keys key1)
        
        (at-robby G1)
        (at-package G6)
        (at-car G3)
        (at-keys G4)
        
        (free-gripper gripper1)
        (free-car car1)
        
        (neighbour G1 G2)
        (neighbour G2 G1)
        (neighbour G2 G3)
        (neighbour G3 G2)
        (neighbour G2 G4)
        (neighbour G4 G2)
        (neighbour G2 G5)
        (neighbour G5 G2)
        (neighbour G5 G6)
        (neighbour G6 G5)
        (neighbour G5 G7)
        (neighbour G7 G5)
        (neighbour G7 G9)
        (neighbour G9 G7)
        (neighbour G9 G10)
        (neighbour G10 G9)
        (neighbour G7 G8)
        (neighbour G8 G7)
    )
    
    (:goal (and (at-robby G1) (at-package G10) (at-car G3) (at-keys G4)))
)